beeclean/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\About;
use app\models\Price;
use app\models\Post;
use app\models\Order;
use app\models\Address;
use app\models\SignupForm;
use app\models\Service;
use app\models\OrderServices;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->layout = 'main2';
        $prices = Price::find()->asArray()->all();
        return $this->render('index', ['prices' => $prices]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if(Yii::$app->user->can('admin'))
            {
                return $this->redirect(['admin/user/index']);
            }else
            {
                return $this->goBack();
            }
        }
        return $this->redirect('index');
    }

    public function actionSignup()
    {
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->user->login($user)) {
                    return $this->redirect(Url::toRoute(['site/dashboard']));
                }
            }
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionBecomeCleaner()
    {
        if(Yii::$app->request->post())
        {
            $full_name = Yii::$app->request->post('full_name');
            $birth_date = Yii::$app->request->post('birth_date');
            $phone = Yii::$app->request->post('phone');

            Yii::$app->mailer->compose('contact_me', compact('full_name', 'birth_date', 'phone', 'body'))
            ->setFrom('noReply@beeclean.com')
            ->setTo(Yii::$app->params['adminEmail'])
            ->setSubject('Хочу быть частью команды Beeclean')
            ->send();
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $this->layout = 'main2';
        $model = About::findOne(1);
        return $this->render('about', ['model' => $model]);
    }

    /**
     * Displays becleaner page.
     *
     * @return string
     */
    public function actionBecleaner()
    {
        return $this->render('becleaner');
    }

    /**
     * Displays blog page.
     *
     * @return string
     */
    public function actionBlog()
    {
        $posts = Post::find()->all();
        return $this->render('blog', ['posts' => $posts]);
    }

    /**
     * Displays copyright page.
     *
     * @return string
     */
    public function actionCopyright()
    {
        return $this->render('copyright');
    }

    /**
     * Displays dashboard-single-item page.
     *
     * @return string
     */
    public function actionDashboardSingleItem()
    {
        if(!Yii::$app->user->isGuest)
        {
            $prices = Price::find()->asArray()->all();
            return $this->render('dashboard-single-item', ['prices' => $prices]);
        }else
        {
            $this->redirect('index');
        }
    }

    /**
     * Displays dashboard page.
     *
     * @return string
     */
    public function actionDashboard()
    {
        if(!Yii::$app->user->isGuest)
        {
            $prices = Price::find()->asArray()->all();
            return $this->render('dashboard', ['prices' => $prices]);
        }else
        {
            $this->redirect('index');
        }
    }

    /**
     * Displays faq page.
     *
     * @return string
     */
    public function actionFaq()
    {
        return $this->render('faq');
    }

    /**
     * Displays order-form page.
     *
     * @return string
     */
    public function actionOrderForm()
    {
        $this->layout = 'main2';
        $prices = Price::find()->asArray()->all();
        $services = Service::find()->asArray()->all();
        return $this->render('order-form', ['prices' => $prices, 'services' => $services]);
    }

    /**
     * Displays sitemap page.
     *
     * @return string
     */
    public function actionSitemap()
    {
        return $this->render('sitemap');
    }

    public function actionOrder()
    {
        $order = new Order();
        $address = new Address();
        if(!Yii::$app->user->isGuest && $order->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post()))
        {
            $address->user_id = Yii::$app->user->identity->id;
            $address->save();

            $order->address_id = $address->id;
            $order->date_time = (new \DateTime())->format('Y-m-d H-i-s');
            $price = Price::find()->where(['bathrooms' => $address->bathrooms, 'rooms' => $address->rooms])->one();
            $order->cost = $price->price;
            $order->status = 'Новый';
            $order->is_regular = (isset($order->is_regular))?1:0;
            $order->save();
            foreach ($order->services as $key => $value) 
            {
                $service = Service::findOne($key);
                (new OrderServices(['order_id' => $order->id, 'service_id' => $service->id]))->save();
                $order->cost += $service->price;
            }
            $order->save();
            $this->redirect('dashboard');
        }else
        {
            $this->redirect(Yii::$app->request->referrer);
        }
    }
}

beeclean/views/site/about.php
<?php
use yii\helpers\Url;
?>
<section class="container-fluid section-first" data-parallax="scroll" data-image-src="<?=  Url::to('@web/img/about.jpg')?>" >
    <div class="container">
        <div class="row about">
            <div class="about__text col-md-6">
                <?= $model!=null?$model->body:''; ?>
            </div>
        </div>

    </div>
</section>
<section class="container-fluid contacts">
    <div class="container">
        <h1 class="ui_h1">Контактная информация</h1>
        <div class="row">
            <div class="col-md-4  col-xs-12 contacts-item">
                <span  class="material-icons">&#xE0BE;</span> <span class="contacts-item__text">mail@mail.ru</span>
            </div>
            <div class="col-md-4  col-xs-12 contacts-item">
                <span class="material-icons">&#xE0B0;</span> <span class="contacts-item__text">9379992</span>
            </div>
            <div class="col-md-4  col-xs-12 contacts-item">
                <span  class="material-icons">&#xE0C8;</span> <span class="contacts-item__text">ул. Example, 163 г. Днепр, 49000</span>
            </div>

        </div>

    </div>


</section>
<section class="container-fluid map">

</section>
<div class="container-fluid">
    <div class="container">
        <div class="col-md-4 col-xs-12 col-md-offset-4">
            <a href="<?= Url::to(['site/order-form']); ?>" style="display: inline-block; text-align: center;" class="section-fourth_btn ui_btn ui_btn_inverse">Подать заявку сейчас</a>
        </div>
    </div>
</div>

beeclean/views/site/becleaner.php
<?php
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>
<section class="container-fluid section-first" data-parallax="scroll" data-image-src="<?=  Url::to('@web/img/cleaner.jpg')?>" >
    <div class="container">

        <div class="info-block row">
            <div class="col-md-offset-2 col-md-4 col-xs-12  info-block-text">
                <div class="info-block-text-main half">
                    Ищем специалистов по уборке в  Днепре
                </div>
                <div class="info-block-text-additional">
                    Отправьте заявку и мы ответим вам в течении 24 часов
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <div class="info-block-form">
                    <?php ActiveForm::begin(['action' => ['site/become-cleaner']]); ?>
                        <div class="info-block-form__title">Расскажите о себе</div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE7FD;</button>
                            <input name="full_name" type="text" class="info-block-form-item__info ui_input tal" placeholder="Ф.И.О.">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE916;</button>
                            <input name="birth_date" type="text" class="info-block-form-item__info ui_input tal" placeholder="Дата рождения">

                        </div>
                        <div class="info-block-form-item">
                            <div class="info-block-form-item__btn info-block-form-item__btn_tel material-icons">&#xE0B0;</div>
                            <input name="phone" class="info-block-form-item__info ui_input tal" type="tel" pattern="\([0-9]{3}\)\s[0-9]{3}-[0-9]{2}-[0-9]{2}" name="phone" placeholder="(050) 121-34-57" title="Формат ввода (050) 121-34-57" required/>

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__info ui_btn" type="submit">Отправить заявку</button>
                        </div>
                    <?php ActiveForm::end(); ?>
                </div>

            </div>
        </div>
        <a href="#section2" class="next-section hidden-xs">Наши преимущества</a>
    </div>
</section>
<section class="container-fluid section-second" id="section2">
    <div class="container">
        <div class="row benefits-list">
            <div class="col-md-4  col-xs-12 benefits-list-item">
                <div class="benefits-list-item__image material-icons">&#xE916;</div>
                <div class="benefits-list-item__title">Гибкий график</div>
                <div class="benefits-list-item__description">Вы решаете, где и за какую ценуделать уборку, а также можетерасписать свою занятость нанеделю вперед</div>
            </div>
            <div class="col-md-4  col-xs-12 benefits-list-item">
                <div class="benefits-list-item__image material-icons">&#xE80C;</div>
                <div class="benefits-list-item__title">Стандартное обучение</div>
                <div class="benefits-list-item__description">Если вы чего-то не умеете, мыобязательно вас научим набесплатных тренингах и курсах</div>
            </div>
            <div class="col-md-4  col-xs-12 benefits-list-item">
                <div class="benefits-list-item__image material-icons">&#xE227;</div>
                <div class="benefits-list-item__title">Регулярные выплаты</div>
                <div class="benefits-list-item__description">Вы всегда видите, сколько ужезаработали. Деньги поступаютна карту два раза в месяц</div>
            </div>

        </div>
        <div class="row benefits-list">
            <div class="col-md-4  col-xs-12 benefits-list-item">
                <div class="benefits-list-item__image material-icons">&#xE8DC;</div>
                <div class="benefits-list-item__title">Бесплатный инвентарь</div>
                <div class="benefits-list-item__description">Мы выдадим вам формуи все необходимое для уборки.Бесплатно пополнить запасыможно в офисе</div>
            </div>
            <div class="col-md-4  col-xs-12 benefits-list-item">
                <div class="benefits-list-item__image material-icons">&#xEB3C;</div>
                <div class="benefits-list-item__title">Выездная работа</div>
                <div class="benefits-list-item__description">Вы можете выбирать заказытолько рядом с вами исоставлять удобныйдля себя маршрут</div>
            </div>
            <div class="col-md-4  col-xs-12 benefits-list-item">
                <div class="benefits-list-item__image material-icons">&#xE32A;</div>
                <div class="benefits-list-item__title">Страховой фонд</div>
                <div class="benefits-list-item__description">Если что-то пойдет не так, вы неостанетесь один на один снеобходимостью покрытьклиенту ущерб</div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-xs-12 col-md-offset-4">
        <button class="section-fourth_btn ui_btn ui_btn_inverse">Подать заявку сейчас</button>
    </div>

</section>

beeclean/views/site/blog.php
<?php
use yii\helpers\Url;
?>
<section class="blog container-fluid">
    <div class="container">
        <h1 class="blog-title ui_h1">
            Блог
        </h1>
        <div class="row hidden-sm hidden-xs">
        <?php foreach($posts as $post): ?>
            <a href ="<?= Url::to(['site/post', 'id' => $post->id]); ?>" class="blog-item">
                <div class="blog-item__img col-md-2 col-lg-2 col-xs-12">
                    <img src="<?= Url::to('@web/'.$post->image_path); ?>" class="img-responsive" alt="">
                </div>
                <div class="blog-item-content col-md-4 col-xs-12">
                    <div class="blog-item-content__title">
                        <?= $post->title; ?>
                    </div>
                    <div class="blog-item-content__excerpt">
                        И при этом сохранить бюджет
                    </div>
                    <div class="blog-item-content__date">
                        <?= $post->date; ?>
                    </div>
                </div>
            </a>
        <?php endforeach; ?>

        </div>
        <div class="row hidden-sm hidden-xs">
            <div class="col-md-4 col-xs-12 col-md-offset-4 ui_tac">
                <button class="section-sixth_btn ui_btn ">Показать еще</button>
            </div>
        </div>

        <div class="swiper-container visible-xs visible-sm">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <div class="swiper-slide ">
                    <a href ="#" class="blog-item">
                        <div class="blog-item__img col-md-2 col-lg-2 col-xs-12">
                            <img src="img/blog-img.png"  alt="">
                        </div>
                        <div class="blog-item-content col-md-4 col-xs-12">
                            <div class="blog-item-content__title">
                                6 способов заставить квартиру выглядеть достойно
                            </div>
                            <div class="blog-item-content__excerpt">
                                И при этом сохранить бюджет
                            </div>
                            <div class="blog-item-content__date">
                                16 августа
                            </div>

                        </div>

                    </a>
                </div>
                <div class="swiper-slide ">
                    <a href ="#" class="blog-item">
                        <div class="blog-item__img col-md-2 col-lg-2 col-xs-12">
                            <img src="img/blog-img.png"  alt="">
                        </div>
                        <div class="blog-item-content col-md-4 col-xs-12">
                            <div class="blog-item-content__title">
                                6 способов заставить квартиру выглядеть достойно
                            </div>
                            <div class="blog-item-content__excerpt">
                                И при этом сохранить бюджет
                            </div>
                            <div class="blog-item-content__date">
                                16 августа
                            </div>

                        </div>

                    </a>
                </div>
                <div class="swiper-slide ">
                    <a href ="#" class="blog-item">
                        <div class="blog-item__img col-md-2 col-lg-2 col-xs-12">
                            <img src="img/blog-img.png"  alt="">
                        </div>
                        <div class="blog-item-content col-md-4 col-xs-12">
                            <div class="blog-item-content__title">
                                6 способов заставить квартиру выглядеть достойно
                            </div>
                            <div class="blog-item-content__excerpt">
                                И при этом сохранить бюджет
                            </div>
                            <div class="blog-item-content__date">
                                16 августа
                            </div>

                        </div>

                    </a>
                </div>

            </div>


        </div>
    </div>
</section>

beeclean/views/site/copyright.php
<section class="copyright container-fluid">
    <div class="container">
        <h1 class="copyright__title ui_h1">
            Пользовательское соглашения
        </h1>
        <p class="ui_p ui_tac">Днепр, Украина, Версия 1.2 от 04 апреля 2016 г.</p>

        <div class="row">
            <div class="col-md-10 copyright__text col-md-offset-1">
                <p class="ui_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aspernatur atque consequatur consequuntur corporis delectus dolores, ex facere fuga in iste pariatur possimus quas repudiandae, sequi tempora temporibus velit voluptatum.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet consequatur corporis culpa, dignissimos dolores error id in libero minus modi necessitatibus officia pariatur perspiciatis placeat ratione recusandae saepe voluptate. Quaerat!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur consequuntur dolor, eius eligendi eos est eveniet exercitationem in laboriosam neque odit porro praesentium, quia repudiandae rerum sapiente sunt veniam voluptate.
                </p>

                <h2 class="ui_h2">
                    1. Общие положения пользовательского соглашения
                </h2>
                <p class="ui_p">
                    1.1.	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                </p>
                <p class="ui_p">1.2.	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                <h2 class="ui_h2">
                    1. Общие положения пользовательского соглашения
                </h2>
                <p class="ui_p">
                    1.1.	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                </p>
                <p class="ui_p">1.2.	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                <h2 class="ui_h2">
                    1. Общие положения пользовательского соглашения
                </h2>
                <p class="ui_p">
                    1.1.	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                </p>
                <p class="ui_p">1.2.	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>

            </div>


        </div>
    </div>


</section>

beeclean/views/site/dashboard.php
<?php
use yii\helpers\Url;
?>
<section class="dashboard container-fluid">
    <div class="container">
        <h1 class="dashboard__title ui_h1">
            Личный кабинет
        </h1>
        <div class="row">
            <ul class="tabs-control col-md-6 col-md-offset-3">
                <li class="tabs-control__item primary" ><span>Основное</span></li><li class="tabs-control__item" ><span>Адреса</span> </li>
            </ul>
        </div>

        <ul class="tabs-list">
            <li class="tabs-list__item active dashboard-content">
                <div class="row">
                    <div class="col-md-2">
                        <div class="dashboard-content__image" style="background-image: url('<?=  Url::to('@web/img/telo4ka.png')?>')">
                        </div>

                    </div>
                    <div class="col-md-4 col-md-offset-1">
                        <!-- <div class="dashboard-content__option">Имя</div>
                        <div class="dashboard-content__value">Мария Цымбал</div> -->
                        <div class="dashboard-content__option">Логин</div>
                        <div class="dashboard-content__value"><?= Yii::$app->user->identity->login; ?></div>
                        <div class="dashboard-content__option">Електронная почта</div>
                        <div class="dashboard-content__value"><?= Yii::$app->user->identity->email; ?></div>
                        <div class="dashboard-content__option">Телефон</div>
                        <div class="dashboard-content__value"><?= Yii::$app->user->identity->phone; ?></div>
                    </div>
                    <div class="col-md-4 col-md-offset-1">
                        <button class="ui_btn dashboard-content__btn" id="dashboard-change">Редактировать</button>
                        <button class="ui_btn dashboard-content__btn" id="password-change">Сменить пароль</button>
                    </div>

                </div>

            </li>
            <li class="tabs-list__item">
                <div class="dashboard-address">


                    <div class="row dashboard-address__head dashboard-address-item">
                        <div class="col-md-1 col-xs-2">
                            Id
                        </div>
                        <div class="col-md-11 col-xs-10">
                            Адресс
                        </div>
                    </div>


                    <!-- список адресов по 10 штук-->
                    <?php foreach(Yii::$app->user->identity->addresses as $address): ?>
                        <div class="row dashboard-address-item">
                            <a data-adress-modal="<?= $address->id; ?>" style="cursor: pointer">
                                <div class="col-md-1 col-xs-2"><?= $address->id; ?></div>
                                <div class="col-md-11 col-xs-10"><?= 'г. '.$address->city.', '.$address->street.' '.$address->house.' кв.'.$address->apartment; ?></div>
                            </a>
                        </div>
                    <?php endforeach; ?>

                    <!-- -->


                    <ul class="dashboard-pagination">
                        <li class="dashboard-pagination__item material-icons navigation">&#xE314;</li>
                        <li class="dashboard-pagination__item">1</li>
                        <li class="dashboard-pagination__item active">2</li>
                        <li class="dashboard-pagination__item">3</li>
                        <li class="dashboard-pagination__item material-icons navigation">&#xE315;</li>

                    </ul>

                </div>

            </li>
        </ul>

    </div>


</section>

<div class="modal-layout" id="change-data">
    <div class="modal-layout__close"></div>

    <div class="modal-window">
        <div class="material-icons modal-close">&#xE5C9;</div>
        <div class="info-block-form ">
            <div class="info-block-form-item">
                <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE7FD;</button>
                <input type="text" class="info-block-form-item__info ui_input tal" placeholder="Имя">

            </div>
            <div class="info-block-form-item">
                <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE7FD;</button>
                <input type="text" class="info-block-form-item__info ui_input tal" placeholder="Фамилия">

            </div>
            <div class="info-block-form-item">
                <div class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0BE;</div>
                <input type="text" class="info-block-form-item__info ui_input tal" placeholder="Почта">

            </div>
            <div class="info-block-form-item">
                <div class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0B0;</div>
                <input type="text" class="info-block-form-item__info ui_input tal" placeholder="Телфон">
            </div>
            <div class="info-block-form-item">
                <div class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE916;</div>
                <input type="text" class="info-block-form-item__info ui_input tal" placeholder="Адресс">
            </div>

            <div class="info-block-form-item">
                <button class="info-block-form-item__info ui_btn" type="submit">Сохранить</button>
            </div>
        </div>
    </div>
</div>
<div class="modal-layout" id="password-data">
    <div class="modal-layout__close"></div>

    <div class="modal-window">
        <div class="material-icons modal-close">&#xE5C9;</div>
        <div class="info-block-form ">
            <div class="info-block-form-item">
                <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE0DA;</button>
                <input type="password" class="info-block-form-item__info ui_input tal" placeholder="Старый пароль">

            </div>
            <div class="info-block-form-item">
                <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                <input type="password" class="info-block-form-item__info ui_input tal" placeholder="Новый пароль">

            </div>
            <div class="info-block-form-item">
                <div class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</div>
                <input type="password" class="info-block-form-item__info ui_input tal" placeholder="Новый пароль еще раз">

            </div>


            <div class="info-block-form-item">
                <button class="info-block-form-item__info ui_btn" type="submit">Сохранить</button>
            </div>
        </div>
    </div>
</div>


<script>
    window.onload = function(){

    }
</script>

beeclean/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>