beeclean/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\About;
use app\models\Price;
use app\models\Post;
use app\models\Order;
use app\models\Address;
use app\models\SignupForm;
use app\models\Service;
use app\models\OrderServices;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->layout = 'main2';
        $prices = Price::find()->asArray()->all();
        return $this->render('index', ['prices' => $prices]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if(Yii::$app->user->can('admin'))
            {
                return $this->redirect(['admin/user/index']);
            }else
            {
                return $this->goBack();
            }
        }
        return $this->redirect('index');
    }

    public function actionSignup()
    {
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->user->login($user)) {
                    return $this->redirect(Url::toRoute(['site/dashboard']));
                }
            }
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionBecomeCleaner()
    {
        if(Yii::$app->request->post())
        {
            $full_name = Yii::$app->request->post('full_name');
            $birth_date = Yii::$app->request->post('birth_date');
            $phone = Yii::$app->request->post('phone');

            Yii::$app->mailer->compose('contact_me', compact('full_name', 'birth_date', 'phone', 'body'))
            ->setFrom('noReply@beeclean.com')
            ->setTo(Yii::$app->params['adminEmail'])
            ->setSubject('Хочу быть частью команды Beeclean')
            ->send();
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $this->layout = 'main2';
        $model = About::findOne(1);
        return $this->render('about', ['model' => $model]);
    }

    /**
     * Displays becleaner page.
     *
     * @return string
     */
    public function actionBecleaner()
    {
        return $this->render('becleaner');
    }

    /**
     * Displays blog page.
     *
     * @return string
     */
    public function actionBlog()
    {
        $posts = Post::find()->all();
        return $this->render('blog', ['posts' => $posts]);
    }

    /**
     * Displays copyright page.
     *
     * @return string
     */
    public function actionCopyright()
    {
        return $this->render('copyright');
    }

    /**
     * Displays dashboard-single-item page.
     *
     * @return string
     */
    public function actionDashboardSingleItem()
    {
        if(!Yii::$app->user->isGuest)
        {
            $prices = Price::find()->asArray()->all();
            return $this->render('dashboard-single-item', ['prices' => $prices]);
        }else
        {
            $this->redirect('index');
        }
    }

    /**
     * Displays dashboard page.
     *
     * @return string
     */
    public function actionDashboard()
    {
        if(!Yii::$app->user->isGuest)
        {
            $prices = Price::find()->asArray()->all();
            return $this->render('dashboard', ['prices' => $prices]);
        }else
        {
            $this->redirect('index');
        }
    }

    /**
     * Displays faq page.
     *
     * @return string
     */
    public function actionFaq()
    {
        return $this->render('faq');
    }

    /**
     * Displays order-form page.
     *
     * @return string
     */
    public function actionOrderForm()
    {
        $this->layout = 'main2';
        $prices = Price::find()->asArray()->all();
        $services = Service::find()->asArray()->all();
        return $this->render('order-form', ['prices' => $prices, 'services' => $services]);
    }

    /**
     * Displays sitemap page.
     *
     * @return string
     */
    public function actionSitemap()
    {
        return $this->render('sitemap');
    }

    public function actionOrder()
    {
        $order = new Order();
        $address = new Address();
        if(!Yii::$app->user->isGuest && $order->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post()))
        {
            $address->user_id = Yii::$app->user->identity->id;
            $address->save();

            $order->address_id = $address->id;
            $order->date_time = (new \DateTime())->format('Y-m-d H-i-s');
            $price = Price::find()->where(['bathrooms' => $address->bathrooms, 'rooms' => $address->rooms])->one();
            $order->cost = $price->price;
            $order->status = 'Новый';
            $order->is_regular = (isset($order->is_regular))?1:0;
            $order->save();
            foreach ($order->services as $key => $value) 
            {
                $service = Service::findOne($key);
                (new OrderServices(['order_id' => $order->id, 'service_id' => $service->id]))->save();
                $order->cost += $service->price;
            }
            $order->save();
            $this->redirect('dashboard');
        }else
        {
            $this->redirect(Yii::$app->request->referrer);
        }
    }
}

beeclean/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\models\Price;
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

AppAsset::register($this);
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="<?=  Url::to('@web/css/main.css')?>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <script src="<?=  Url::to('@web/js/main.js')?>"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
</head>
<body>
<header class="header static container-fluid">
    <div class="container">
        <a href="<?= Url::to(['site/index']); ?>" class="header-logo"></a>

        <ul class="header-menu hidden-xs">
            <li class="header-menu-item"><a href="<?= Url::to(['site/about']); ?>">О сервисе</a></li>
            <li class="header-menu-item"><a href="<?= Url::to(['site/faq']); ?>">Вопросы и ответы</a></li>
            <li class="header-menu-item" style="display: none;"><a href="#" id="login_btn">Войти</a></li>
            <?php if(!Yii::$app->user->isGuest): ?>
                <li class="header-menu-item">
                    <?php ActiveForm::begin(['action' => ['site/logout']]); ?>
                        <button type="submit">Выйти (<span><?= Yii::$app->user->identity->login; ?></span>)</button>
                    <?php ActiveForm::end(); ?>
                </li>
            <?php endif; ?>
        </ul>

        <div class="header-dropdown visible-xs">
            <button class="header-dropdown-btn btn " type="button" id="button-menu">
                <span class="material-icons">&#xE5D2;</span>
            </button>
            <ul class="header-dropdown-menu">
                <li ><a href="<?= Url::to(['site/about']); ?>">О сервисе</a></li>
                <li><a href="<?= Url::to(['site/faq']); ?>">Вопросы и ответы</a></li>
                <li style="display: none;"><a href="#" id="login_btn_small">Войти</a></li>
                <?php if(!Yii::$app->user->isGuest): ?>
                    <li>
                        <?php ActiveForm::begin(['action' => ['site/logout']]); ?>
                            <button>Выйти (<span><?= Yii::$app->user->identity->login; ?></span>)</button>
                        <?php ActiveForm::end(); ?>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <div class="ui-ic header-tel" data-ic="&#xE0B0;">(099) 937 9992</div>
    </div>
</header>

<?= $content; ?>

<footer class="footer" data-parallax="scroll"  data-image-src="<?=  Url::to('@web/img/section-7.jpg')?>">
    <section class="section-seventh container-fluid">
        <div class="row">
            <h1 class="section-seventh__title ui_tac">
                Уборка квартиры от 3000 грн.
            </h1>
        </div>
        <div class="row">
            <div class="section-seventh__description col-md-4 col-xs-12 col-sm-8 col-sm-offset-2 col-md-offset-4 ui_tac">
                Мы готовы приехать к вам уже сегодня
            </div>
        </div>

    </section>
    <section class="main-footer container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-3 col-md-3 col-sm-offset-1 col-sm-5 col-xs-12 ">

                    <h2 class="main-footer__title">BeeClean</h2>

                    <ul class="main-footer-list">
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/about']); ?>">О сервисе</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/faq']); ?>">Вопросы и ответы</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/blog']); ?>">Блог</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/becleaner']); ?>">Работа в BeeClean</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/sitemap']); ?>">Карта сайта</a></li>
                    </ul>

                </div>

                <div class=" col-md-3 col-sm-5  col-xs-12 ">
                    <h2 class="main-footer__title">Свяжитесь с нами</h2>

                    <ul class="main-footer-contacts">
                        <li class="main-footer-contacts__item ui-ic" data-ic="&#xE0BE;">feedback@beclean.com</li>
                        <li class="main-footer-contacts__item ui-ic" data-ic="&#xE0B0;">(099) 937 9992</li>

                    </ul>
                    <h2 class="main-footer__title">Свяжитесь с нами</h2>
                    <ul class="main-footer-social">
                        <li class="main-footer-social-item fb"><a href="#"></a></li>
                        <li class="main-footer-social-item tl"><a href="#"></a></li>
                        <li class="main-footer-social-item is"><a href="#"></a></li>
                        <li class="main-footer-social-item vk"><a href="#"></a></li>
                    </ul>
                </div>


            </div>
            <div class="row">
                <div class="col-md-offset-3 col-md-3 main-footer-logo">
                    <img src="<?=  Url::to('@web/img/logo.png')?>" alt="" class="img-responsive">
                </div>
                <div class="col-md-3 main-footer-copyright">
                    @2016 Beclean
                </div>
            </div>
        </div>
    </section>


<div class="modal-layout" id="login">
    <div class="modal-layout__close"></div>
    <div class="modal-window">
        <div class="material-icons modal-close">&#xE5C9;</div>

        <div class="info-block-form">
            <ul class="tabs-control">
                <li class="tabs-control__item primary"><span>Логин</span></li><li class="tabs-control__item" ><span>Регистрация</span> </li>
            </ul>
            <ul class="tabs-list">

                    <li class="tabs-list__item active">
                        <?php ActiveForm::begin(['action' => ['site/login']]); ?>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE7FD;</button>
                            <input name="LoginForm[login]" class="info-block-form-item__info ui_input tal" placeholder="Логин">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                            <input name="LoginForm[password]" type="password" class="info-block-form-item__info ui_input tal" placeholder="Пароль">

                        </div>



                        <div class="info-block-form-item">
                            <button class="info-block-form-item__info ui_btn" type="submit">Войти</button>
                        </div>
                        <?php ActiveForm::end(); ?>

                    </li>


                    <li class="tabs-list__item">
                        <?php ActiveForm::begin(['action' => ['site/signup']]); ?>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE7FD;</button>
                            <input name="SignupForm[login]" class="info-block-form-item__info ui_input tal" placeholder="Логин">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                            <input type="password" name="SignupForm[password]" class="info-block-form-item__info ui_input tal" placeholder="Пароль">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                            <input type="password" class="info-block-form-item__info ui_input tal" placeholder="Повторите пароль">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0B0;</button>
                            <input name="SignupForm[phone]" class="info-block-form-item__info ui_input tal" placeholder="Номер телефона">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0BE;</button>
                            <input name="SignupForm[email]" class="info-block-form-item__info ui_input tal" placeholder="Е-мейл">

                        </div>


                        <div class="info-block-form-item" >
                            <label  class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">
                                <input type="checkbox" class="info-block-form-item__checkbox">
                            </label>
                            <div type="text" class="info-block-form-item__info ui_input tal ui_p"> Я прочел <a style="text-decoration: underline;" href="<?= Url::to(['site/copyright']); ?>">СОГЛАШЕНИЕ</a></div>
                        </div>



                        <div class="info-block-form-item">
                            <button class="info-block-form-item__info ui_btn" type="submit">Зарегистрироваться</button>
                        </div>
                        <?php ActiveForm::end(); ?>

                    </li>

            </ul>


        </div>
    </div>
</div>


    <div class="modal-layout" id="single_adres">
        <div class="modal-layout__close"></div>
        <div class="modal-window" style="min-width: 75%; max-width: 90%">
            <div class="material-icons modal-close">&#xE5C9;</div>

            <div class="info-block-form">
                <div class="dashboard-address" style="padding: 30px; border-radius: 15px;">
                    <div class="dashboard-address__title">
                        г. Днепр, пр. Слобожанский 32/2 кв.532
                    </div>
                    <div class="row dashboard-address__head dashboard-address-item">
                        <div class="col-md-2 col-xs-3">
                            Id
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            Дата
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            Цена
                        </div>
                        <div class="col-md-3 col-md-offset-1 col-xs-3">
                            Статус
                        </div>

                    </div>
                    <div class="row dashboard-address-item">
                        <div class="col-md-2 col-xs-3">
                            59
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            01.02.2015
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            2000грн
                        </div>
                        <div class="col-md-3 col-md-offset-1 done col-xs-3">
                            Выполнено
                        </div>
                    </div>
                    <div class="row dashboard-address-item">
                        <div class="col-md-2 col-xs-3 ">
                            59
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            01.02.2015
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            2000грн
                        </div>
                        <div class="col-md-3 col-md-offset-1 not-done col-xs-3">
                            Не выполнено
                        </div>
                    </div>
                    <div class="row dashboard-address-item">
                        <div class="col-md-2 col-xs-3">
                            59
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            01.02.2015
                        </div>
                        <div class="col-md-2 col-md-offset-1 col-xs-3">
                            2000грн
                        </div>
                        <div class="col-md-3 col-md-offset-1 cancel col-xs-3">
                            Отменен
                        </div>
                    </div>

                    <ul class="dashboard-pagination">
                        <li class="dashboard-pagination__item material-icons navigation">&#xE314;</li>
                        <li class="dashboard-pagination__item">1</li>
                        <li class="dashboard-pagination__item active">2</li>
                        <li class="dashboard-pagination__item">3</li>
                        <li class="dashboard-pagination__item material-icons navigation">&#xE315;</li>

                    </ul>

                </div>
            </div>
        </div>
    </div>

</footer>


<script src="<?=  Url::to('@web/js/parallax.min.js')?>"></script>
</body>
</html>

beeclean/views/layouts/main2.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\models\Price;
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

AppAsset::register($this);
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="<?=  Url::to('@web/css/main.css')?>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <script src="<?=  Url::to('@web/js/main.js')?>"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
</head>
<body>
<header class="header  container-fluid">
    <div class="container">
        <a href="<?= Url::to(['site/index']); ?>" class="header-logo"></a>

        <ul class="header-menu hidden-xs">
            <li class="header-menu-item"><a href="<?= Url::to(['site/about']); ?>">О сервисе</a></li>
            <li class="header-menu-item"><a href="<?= Url::to(['site/faq']); ?>">Вопросы и ответы</a></li>
            <li class="header-menu-item" ><a href="#" id="login_btn">Войти</a></li>
            <?php if(!Yii::$app->user->isGuest): ?>
                <li class="header-menu-item">
                    <?php ActiveForm::begin(['action' => ['site/logout']]); ?>
                        <button type="submit">Выйти (<span><?= Yii::$app->user->identity->login; ?></span>)</button>
                    <?php ActiveForm::end(); ?>
                </li>
            <?php endif; ?>
        </ul>

        <div class="header-dropdown visible-xs">
            <button class="header-dropdown-btn btn " type="button" id="button-menu">
                <span class="material-icons">&#xE5D2;</span>
            </button>
            <ul class="header-dropdown-menu">
                <li><a href="<?= Url::to(['site/about']); ?>">О сервисе</a></li>
                <li><a href="<?= Url::to(['site/faq']); ?>">Вопросы и ответы</a></li>
                <li ><a href="#" id="login_btn_small">Войти</a></li>
                <?php if(!Yii::$app->user->isGuest): ?>
                    <li>
                        <?php ActiveForm::begin(['action' => ['site/logout']]); ?>
                            <button>Выйти (<span><?= Yii::$app->user->identity->login; ?></span>)</button>
                        <?php ActiveForm::end(); ?>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <div class="ui-ic header-tel" data-ic="&#xE0B0;">(099) 937 9992</div>
    </div>
</header>

<?= $content; ?>

<footer class="footer" data-parallax="scroll"  data-image-src="<?=  Url::to('@web/img/section-7.jpg')?>">
    <section class="section-seventh container-fluid">
        <div class="row">
            <h1 class="section-seventh__title ui_tac">
                Уборка квартиры от 3000 грн.
            </h1>
        </div>
        <div class="row">
            <div class="section-seventh__description col-md-4 col-xs-12 col-sm-8 col-sm-offset-2 col-md-offset-4 ui_tac">
                Мы готовы приехать к вам уже сегодня
            </div>
        </div>

    </section>
    <section class="main-footer container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-3 col-md-3 col-sm-offset-1 col-sm-5 col-xs-12 ">

                    <h2 class="main-footer__title">BeeClean</h2>

                    <ul class="main-footer-list">
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/about']); ?>">О сервисе</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/faq']); ?>">Вопросы и ответы</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/blog']); ?>">Блог</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/becleaner']); ?>">Работа в BeeClean</a></li>
                        <li class="main-footer-list__item"><a href="<?= Url::to(['site/sitemap']); ?>">Карта сайта</a></li>
                    </ul>

                </div>

                <div class=" col-md-3 col-sm-5  col-xs-12 ">
                    <h2 class="main-footer__title">Свяжитесь с нами</h2>

                    <ul class="main-footer-contacts">
                        <li class="main-footer-contacts__item ui-ic" data-ic="&#xE0BE;">feedback@beclean.com</li>
                        <li class="main-footer-contacts__item ui-ic" data-ic="&#xE0B0;">(099) 937 9992</li>

                    </ul>
                    <h2 class="main-footer__title">Свяжитесь с нами</h2>
                    <ul class="main-footer-social">
                        <li class="main-footer-social-item fb"><a href="#"></a></li>
                        <li class="main-footer-social-item tl"><a href="#"></a></li>
                        <li class="main-footer-social-item is"><a href="#"></a></li>
                        <li class="main-footer-social-item vk"><a href="#"></a></li>
                    </ul>
                </div>


            </div>
            <div class="row">
                <div class="col-md-offset-3 col-md-3 main-footer-logo">
                    <img src="<?=  Url::to('@web/img/logo.png')?>" alt="" class="img-responsive">
                </div>
                <div class="col-md-3 main-footer-copyright">
                    @2016 Beclean
                </div>
            </div>
        </div>
    </section>


<div class="modal-layout" id="login">
    <div class="modal-layout__close"></div>
    <div class="modal-window">
        <div class="material-icons modal-close">&#xE5C9;</div>

        <div class="info-block-form">
            <ul class="tabs-control">
                <li class="tabs-control__item primary"><span>Логин</span></li><li class="tabs-control__item" ><span>Регистрация</span> </li>
            </ul>
            <ul class="tabs-list">

                    <li class="tabs-list__item active">
                        <?php ActiveForm::begin(['action' => ['site/login']]); ?>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE7FD;</button>
                            <input name="LoginForm[login]" class="info-block-form-item__info ui_input tal" placeholder="Логин">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                            <input name="LoginForm[password]" type="password" class="info-block-form-item__info ui_input tal" placeholder="Пароль">

                        </div>



                        <div class="info-block-form-item">
                            <button class="info-block-form-item__info ui_btn" type="submit">Войти</button>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </li>


                    <li class="tabs-list__item">
                        <?php ActiveForm::begin(['action' => ['site/signup']]); ?>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons" >&#xE7FD;</button>
                            <input name="SignupForm[login]" class="info-block-form-item__info ui_input tal" placeholder="Логин">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                            <input type="password" name="SignupForm[password]" class="info-block-form-item__info ui_input tal" placeholder="Пароль">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0DA;</button>
                            <input type="password" class="info-block-form-item__info ui_input tal" placeholder="Повторите пароль">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0B0;</button>
                            <input name="SignupForm[phone]" class="info-block-form-item__info ui_input tal" placeholder="Номер телефона">

                        </div>
                        <div class="info-block-form-item">
                            <button class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">&#xE0BE;</button>
                            <input name="SignupForm[email]" class="info-block-form-item__info ui_input tal" placeholder="Е-мейл">

                        </div>


                        <div class="info-block-form-item" >
                            <label  class="info-block-form-item__btn info-block-form-item__btn_minus material-icons">
                                <input type="checkbox" class="info-block-form-item__checkbox">
                            </label>
                            <div type="text" class="info-block-form-item__info ui_input tal ui_p"> Я прочел <a style="text-decoration: underline;" href="<?= Url::to(['site/copyright']); ?>">СОГЛАШЕНИЕ</a></div>
                        </div>



                        <div class="info-block-form-item">
                            <button class="info-block-form-item__info ui_btn" type="submit">Зарегистрироваться</button>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </li>

            </ul>


        </div>
    </div>
</div>

</footer>


<script src="<?=  Url::to('@web/js/parallax.min.js')?>"></script>
</body>
</html>